services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  rustfs:
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      ENABLE_HTTPS_REDIRECT: "False"
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      RUSTFS_ENDPOINT: localhost:9000

networks:
  coolify:
    external: false
